/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FirstAidArticle {
  'title' : string,
  'content' : string,
  'steps' : Array<string>,
  'category' : FirstAidCategory,
  'severity' : FirstAidSeverity,
}
export type FirstAidCategory = { 'CPR' : null } |
  { 'bleeding' : null } |
  { 'shock' : null } |
  { 'burns' : null } |
  { 'fractures' : null };
export type FirstAidSeverity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'moderate' : null };
export interface HazardRecord {
  'hazardType' : HazardType,
  'timestamp' : Time,
  'severity' : HazardSeverity,
  'location' : string,
}
export type HazardSeverity = { 'low' : null } |
  { 'severe' : null } |
  { 'extreme' : null } |
  { 'moderate' : null };
export type HazardType = { 'flood' : null } |
  { 'earthquake' : null } |
  { 'fire' : null } |
  { 'chemical' : null };
export type SurvivalCategory = { 'fire' : null } |
  { 'food' : null } |
  { 'navigation' : null } |
  { 'shelter' : null } |
  { 'water' : null };
export interface SurvivalTopic {
  'title' : string,
  'content' : string,
  'tags' : Array<string>,
  'category' : SurvivalCategory,
}
export type Time = bigint;
export interface TriageRecord {
  'status' : TriageStatus,
  'patientId' : string,
  'notes' : string,
  'timestamp' : Time,
  'symptoms' : Array<string>,
}
export type TriageStatus = { 'minor' : null } |
  { 'delayed' : null } |
  { 'deceased' : null } |
  { 'immediate' : null };
export interface _SERVICE {
  'addFirstAidArticle' : ActorMethod<[FirstAidArticle], undefined>,
  'addHazardRecord' : ActorMethod<[HazardRecord], undefined>,
  'addSurvivalTopic' : ActorMethod<[SurvivalTopic], undefined>,
  'addTriageRecord' : ActorMethod<[TriageRecord], undefined>,
  'getAllFirstAidArticles' : ActorMethod<[], Array<FirstAidArticle>>,
  'getAllHazardRecords' : ActorMethod<[], Array<HazardRecord>>,
  'getAllSurvivalTopics' : ActorMethod<[], Array<SurvivalTopic>>,
  'getAllTriageRecords' : ActorMethod<[], Array<TriageRecord>>,
  'getFirstAidArticle' : ActorMethod<[string], FirstAidArticle>,
  'initializeData' : ActorMethod<[], undefined>,
  'searchArticles' : ActorMethod<
    [string],
    { 'survival' : Array<SurvivalTopic>, 'firstAid' : Array<FirstAidArticle> }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];