/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FirstAidCategory = IDL.Variant({
  'CPR' : IDL.Null,
  'bleeding' : IDL.Null,
  'shock' : IDL.Null,
  'burns' : IDL.Null,
  'fractures' : IDL.Null,
});
export const FirstAidSeverity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'moderate' : IDL.Null,
});
export const FirstAidArticle = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'steps' : IDL.Vec(IDL.Text),
  'category' : FirstAidCategory,
  'severity' : FirstAidSeverity,
});
export const HazardType = IDL.Variant({
  'flood' : IDL.Null,
  'earthquake' : IDL.Null,
  'fire' : IDL.Null,
  'chemical' : IDL.Null,
});
export const Time = IDL.Int;
export const HazardSeverity = IDL.Variant({
  'low' : IDL.Null,
  'severe' : IDL.Null,
  'extreme' : IDL.Null,
  'moderate' : IDL.Null,
});
export const HazardRecord = IDL.Record({
  'hazardType' : HazardType,
  'timestamp' : Time,
  'severity' : HazardSeverity,
  'location' : IDL.Text,
});
export const SurvivalCategory = IDL.Variant({
  'fire' : IDL.Null,
  'food' : IDL.Null,
  'navigation' : IDL.Null,
  'shelter' : IDL.Null,
  'water' : IDL.Null,
});
export const SurvivalTopic = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'category' : SurvivalCategory,
});
export const TriageStatus = IDL.Variant({
  'minor' : IDL.Null,
  'delayed' : IDL.Null,
  'deceased' : IDL.Null,
  'immediate' : IDL.Null,
});
export const TriageRecord = IDL.Record({
  'status' : TriageStatus,
  'patientId' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'symptoms' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addFirstAidArticle' : IDL.Func([FirstAidArticle], [], []),
  'addHazardRecord' : IDL.Func([HazardRecord], [], []),
  'addSurvivalTopic' : IDL.Func([SurvivalTopic], [], []),
  'addTriageRecord' : IDL.Func([TriageRecord], [], []),
  'getAllFirstAidArticles' : IDL.Func(
      [],
      [IDL.Vec(FirstAidArticle)],
      ['query'],
    ),
  'getAllHazardRecords' : IDL.Func([], [IDL.Vec(HazardRecord)], ['query']),
  'getAllSurvivalTopics' : IDL.Func([], [IDL.Vec(SurvivalTopic)], ['query']),
  'getAllTriageRecords' : IDL.Func([], [IDL.Vec(TriageRecord)], ['query']),
  'getFirstAidArticle' : IDL.Func([IDL.Text], [FirstAidArticle], ['query']),
  'initializeData' : IDL.Func([], [], []),
  'searchArticles' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'survival' : IDL.Vec(SurvivalTopic),
          'firstAid' : IDL.Vec(FirstAidArticle),
        }),
      ],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FirstAidCategory = IDL.Variant({
    'CPR' : IDL.Null,
    'bleeding' : IDL.Null,
    'shock' : IDL.Null,
    'burns' : IDL.Null,
    'fractures' : IDL.Null,
  });
  const FirstAidSeverity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const FirstAidArticle = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'steps' : IDL.Vec(IDL.Text),
    'category' : FirstAidCategory,
    'severity' : FirstAidSeverity,
  });
  const HazardType = IDL.Variant({
    'flood' : IDL.Null,
    'earthquake' : IDL.Null,
    'fire' : IDL.Null,
    'chemical' : IDL.Null,
  });
  const Time = IDL.Int;
  const HazardSeverity = IDL.Variant({
    'low' : IDL.Null,
    'severe' : IDL.Null,
    'extreme' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const HazardRecord = IDL.Record({
    'hazardType' : HazardType,
    'timestamp' : Time,
    'severity' : HazardSeverity,
    'location' : IDL.Text,
  });
  const SurvivalCategory = IDL.Variant({
    'fire' : IDL.Null,
    'food' : IDL.Null,
    'navigation' : IDL.Null,
    'shelter' : IDL.Null,
    'water' : IDL.Null,
  });
  const SurvivalTopic = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'category' : SurvivalCategory,
  });
  const TriageStatus = IDL.Variant({
    'minor' : IDL.Null,
    'delayed' : IDL.Null,
    'deceased' : IDL.Null,
    'immediate' : IDL.Null,
  });
  const TriageRecord = IDL.Record({
    'status' : TriageStatus,
    'patientId' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'symptoms' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addFirstAidArticle' : IDL.Func([FirstAidArticle], [], []),
    'addHazardRecord' : IDL.Func([HazardRecord], [], []),
    'addSurvivalTopic' : IDL.Func([SurvivalTopic], [], []),
    'addTriageRecord' : IDL.Func([TriageRecord], [], []),
    'getAllFirstAidArticles' : IDL.Func(
        [],
        [IDL.Vec(FirstAidArticle)],
        ['query'],
      ),
    'getAllHazardRecords' : IDL.Func([], [IDL.Vec(HazardRecord)], ['query']),
    'getAllSurvivalTopics' : IDL.Func([], [IDL.Vec(SurvivalTopic)], ['query']),
    'getAllTriageRecords' : IDL.Func([], [IDL.Vec(TriageRecord)], ['query']),
    'getFirstAidArticle' : IDL.Func([IDL.Text], [FirstAidArticle], ['query']),
    'initializeData' : IDL.Func([], [], []),
    'searchArticles' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'survival' : IDL.Vec(SurvivalTopic),
            'firstAid' : IDL.Vec(FirstAidArticle),
          }),
        ],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };