/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FirstAidArticle {
    title: string;
    content: string;
    steps: Array<string>;
    category: FirstAidCategory;
    severity: FirstAidSeverity;
}
export interface TriageRecord {
    status: TriageStatus;
    patientId: string;
    notes: string;
    timestamp: Time;
    symptoms: Array<string>;
}
export type Time = bigint;
export interface HazardRecord {
    hazardType: HazardType;
    timestamp: Time;
    severity: HazardSeverity;
    location: string;
}
export interface SurvivalTopic {
    title: string;
    content: string;
    tags: Array<string>;
    category: SurvivalCategory;
}
export enum FirstAidCategory {
    CPR = "CPR",
    bleeding = "bleeding",
    shock = "shock",
    burns = "burns",
    fractures = "fractures"
}
export enum FirstAidSeverity {
    low = "low",
    high = "high",
    critical = "critical",
    moderate = "moderate"
}
export enum HazardSeverity {
    low = "low",
    severe = "severe",
    extreme = "extreme",
    moderate = "moderate"
}
export enum HazardType {
    flood = "flood",
    earthquake = "earthquake",
    fire = "fire",
    chemical = "chemical"
}
export enum SurvivalCategory {
    fire = "fire",
    food = "food",
    navigation = "navigation",
    shelter = "shelter",
    water = "water"
}
export enum TriageStatus {
    minor = "minor",
    delayed = "delayed",
    deceased = "deceased",
    immediate = "immediate"
}
export interface backendInterface {
    addFirstAidArticle(article: FirstAidArticle): Promise<void>;
    addHazardRecord(record: HazardRecord): Promise<void>;
    addSurvivalTopic(topic: SurvivalTopic): Promise<void>;
    addTriageRecord(record: TriageRecord): Promise<void>;
    getAllFirstAidArticles(): Promise<Array<FirstAidArticle>>;
    getAllHazardRecords(): Promise<Array<HazardRecord>>;
    getAllSurvivalTopics(): Promise<Array<SurvivalTopic>>;
    getAllTriageRecords(): Promise<Array<TriageRecord>>;
    getFirstAidArticle(title: string): Promise<FirstAidArticle>;
    initializeData(): Promise<void>;
    searchArticles(searchTerm: string): Promise<{
        survival: Array<SurvivalTopic>;
        firstAid: Array<FirstAidArticle>;
    }>;
}
import type { FirstAidArticle as _FirstAidArticle, FirstAidCategory as _FirstAidCategory, FirstAidSeverity as _FirstAidSeverity, HazardRecord as _HazardRecord, HazardSeverity as _HazardSeverity, HazardType as _HazardType, SurvivalCategory as _SurvivalCategory, SurvivalTopic as _SurvivalTopic, Time as _Time, TriageRecord as _TriageRecord, TriageStatus as _TriageStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFirstAidArticle(arg0: FirstAidArticle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFirstAidArticle(to_candid_FirstAidArticle_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFirstAidArticle(to_candid_FirstAidArticle_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addHazardRecord(arg0: HazardRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHazardRecord(to_candid_HazardRecord_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHazardRecord(to_candid_HazardRecord_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSurvivalTopic(arg0: SurvivalTopic): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSurvivalTopic(to_candid_SurvivalTopic_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSurvivalTopic(to_candid_SurvivalTopic_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTriageRecord(arg0: TriageRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTriageRecord(to_candid_TriageRecord_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTriageRecord(to_candid_TriageRecord_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllFirstAidArticles(): Promise<Array<FirstAidArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFirstAidArticles();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFirstAidArticles();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHazardRecords(): Promise<Array<HazardRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHazardRecords();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHazardRecords();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSurvivalTopics(): Promise<Array<SurvivalTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSurvivalTopics();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSurvivalTopics();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTriageRecords(): Promise<Array<TriageRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTriageRecords();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTriageRecords();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFirstAidArticle(arg0: string): Promise<FirstAidArticle> {
        if (this.processError) {
            try {
                const result = await this.actor.getFirstAidArticle(arg0);
                return from_candid_FirstAidArticle_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFirstAidArticle(arg0);
            return from_candid_FirstAidArticle_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeData();
            return result;
        }
    }
    async searchArticles(arg0: string): Promise<{
        survival: Array<SurvivalTopic>;
        firstAid: Array<FirstAidArticle>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.searchArticles(arg0);
                return from_candid_record_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchArticles(arg0);
            return from_candid_record_n45(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_FirstAidArticle_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FirstAidArticle): FirstAidArticle {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_FirstAidCategory_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FirstAidCategory): FirstAidCategory {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_FirstAidSeverity_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FirstAidSeverity): FirstAidSeverity {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_HazardRecord_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HazardRecord): HazardRecord {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_HazardSeverity_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HazardSeverity): HazardSeverity {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_HazardType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HazardType): HazardType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_SurvivalCategory_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SurvivalCategory): SurvivalCategory {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_SurvivalTopic_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SurvivalTopic): SurvivalTopic {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_TriageRecord_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TriageRecord): TriageRecord {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_TriageStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TriageStatus): TriageStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    steps: Array<string>;
    category: _FirstAidCategory;
    severity: _FirstAidSeverity;
}): {
    title: string;
    content: string;
    steps: Array<string>;
    category: FirstAidCategory;
    severity: FirstAidSeverity;
} {
    return {
        title: value.title,
        content: value.content,
        steps: value.steps,
        category: from_candid_FirstAidCategory_n24(_uploadFile, _downloadFile, value.category),
        severity: from_candid_FirstAidSeverity_n26(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hazardType: _HazardType;
    timestamp: _Time;
    severity: _HazardSeverity;
    location: string;
}): {
    hazardType: HazardType;
    timestamp: Time;
    severity: HazardSeverity;
    location: string;
} {
    return {
        hazardType: from_candid_HazardType_n31(_uploadFile, _downloadFile, value.hazardType),
        timestamp: value.timestamp,
        severity: from_candid_HazardSeverity_n33(_uploadFile, _downloadFile, value.severity),
        location: value.location
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    tags: Array<string>;
    category: _SurvivalCategory;
}): {
    title: string;
    content: string;
    tags: Array<string>;
    category: SurvivalCategory;
} {
    return {
        title: value.title,
        content: value.content,
        tags: value.tags,
        category: from_candid_SurvivalCategory_n38(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TriageStatus;
    patientId: string;
    notes: string;
    timestamp: _Time;
    symptoms: Array<string>;
}): {
    status: TriageStatus;
    patientId: string;
    notes: string;
    timestamp: Time;
    symptoms: Array<string>;
} {
    return {
        status: from_candid_TriageStatus_n43(_uploadFile, _downloadFile, value.status),
        patientId: value.patientId,
        notes: value.notes,
        timestamp: value.timestamp,
        symptoms: value.symptoms
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    survival: Array<_SurvivalTopic>;
    firstAid: Array<_FirstAidArticle>;
}): {
    survival: Array<SurvivalTopic>;
    firstAid: Array<FirstAidArticle>;
} {
    return {
        survival: from_candid_vec_n35(_uploadFile, _downloadFile, value.survival),
        firstAid: from_candid_vec_n21(_uploadFile, _downloadFile, value.firstAid)
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    CPR: null;
} | {
    bleeding: null;
} | {
    shock: null;
} | {
    burns: null;
} | {
    fractures: null;
}): FirstAidCategory {
    return "CPR" in value ? FirstAidCategory.CPR : "bleeding" in value ? FirstAidCategory.bleeding : "shock" in value ? FirstAidCategory.shock : "burns" in value ? FirstAidCategory.burns : "fractures" in value ? FirstAidCategory.fractures : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    moderate: null;
}): FirstAidSeverity {
    return "low" in value ? FirstAidSeverity.low : "high" in value ? FirstAidSeverity.high : "critical" in value ? FirstAidSeverity.critical : "moderate" in value ? FirstAidSeverity.moderate : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flood: null;
} | {
    earthquake: null;
} | {
    fire: null;
} | {
    chemical: null;
}): HazardType {
    return "flood" in value ? HazardType.flood : "earthquake" in value ? HazardType.earthquake : "fire" in value ? HazardType.fire : "chemical" in value ? HazardType.chemical : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    severe: null;
} | {
    extreme: null;
} | {
    moderate: null;
}): HazardSeverity {
    return "low" in value ? HazardSeverity.low : "severe" in value ? HazardSeverity.severe : "extreme" in value ? HazardSeverity.extreme : "moderate" in value ? HazardSeverity.moderate : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fire: null;
} | {
    food: null;
} | {
    navigation: null;
} | {
    shelter: null;
} | {
    water: null;
}): SurvivalCategory {
    return "fire" in value ? SurvivalCategory.fire : "food" in value ? SurvivalCategory.food : "navigation" in value ? SurvivalCategory.navigation : "shelter" in value ? SurvivalCategory.shelter : "water" in value ? SurvivalCategory.water : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minor: null;
} | {
    delayed: null;
} | {
    deceased: null;
} | {
    immediate: null;
}): TriageStatus {
    return "minor" in value ? TriageStatus.minor : "delayed" in value ? TriageStatus.delayed : "deceased" in value ? TriageStatus.deceased : "immediate" in value ? TriageStatus.immediate : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FirstAidArticle>): Array<FirstAidArticle> {
    return value.map((x)=>from_candid_FirstAidArticle_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HazardRecord>): Array<HazardRecord> {
    return value.map((x)=>from_candid_HazardRecord_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SurvivalTopic>): Array<SurvivalTopic> {
    return value.map((x)=>from_candid_SurvivalTopic_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TriageRecord>): Array<TriageRecord> {
    return value.map((x)=>from_candid_TriageRecord_n41(_uploadFile, _downloadFile, x));
}
function to_candid_FirstAidArticle_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FirstAidArticle): _FirstAidArticle {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_FirstAidCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FirstAidCategory): _FirstAidCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_FirstAidSeverity_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FirstAidSeverity): _FirstAidSeverity {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_HazardRecord_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HazardRecord): _HazardRecord {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_HazardSeverity_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HazardSeverity): _HazardSeverity {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_HazardType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HazardType): _HazardType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_SurvivalCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SurvivalCategory): _SurvivalCategory {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_SurvivalTopic_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SurvivalTopic): _SurvivalTopic {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_TriageRecord_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TriageRecord): _TriageRecord {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_TriageStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TriageStatus): _TriageStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    tags: Array<string>;
    category: SurvivalCategory;
}): {
    title: string;
    content: string;
    tags: Array<string>;
    category: _SurvivalCategory;
} {
    return {
        title: value.title,
        content: value.content,
        tags: value.tags,
        category: to_candid_SurvivalCategory_n15(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: TriageStatus;
    patientId: string;
    notes: string;
    timestamp: Time;
    symptoms: Array<string>;
}): {
    status: _TriageStatus;
    patientId: string;
    notes: string;
    timestamp: _Time;
    symptoms: Array<string>;
} {
    return {
        status: to_candid_TriageStatus_n19(_uploadFile, _downloadFile, value.status),
        patientId: value.patientId,
        notes: value.notes,
        timestamp: value.timestamp,
        symptoms: value.symptoms
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    steps: Array<string>;
    category: FirstAidCategory;
    severity: FirstAidSeverity;
}): {
    title: string;
    content: string;
    steps: Array<string>;
    category: _FirstAidCategory;
    severity: _FirstAidSeverity;
} {
    return {
        title: value.title,
        content: value.content,
        steps: value.steps,
        category: to_candid_FirstAidCategory_n3(_uploadFile, _downloadFile, value.category),
        severity: to_candid_FirstAidSeverity_n5(_uploadFile, _downloadFile, value.severity)
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hazardType: HazardType;
    timestamp: Time;
    severity: HazardSeverity;
    location: string;
}): {
    hazardType: _HazardType;
    timestamp: _Time;
    severity: _HazardSeverity;
    location: string;
} {
    return {
        hazardType: to_candid_HazardType_n9(_uploadFile, _downloadFile, value.hazardType),
        timestamp: value.timestamp,
        severity: to_candid_HazardSeverity_n11(_uploadFile, _downloadFile, value.severity),
        location: value.location
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HazardType): {
    flood: null;
} | {
    earthquake: null;
} | {
    fire: null;
} | {
    chemical: null;
} {
    return value == HazardType.flood ? {
        flood: null
    } : value == HazardType.earthquake ? {
        earthquake: null
    } : value == HazardType.fire ? {
        fire: null
    } : value == HazardType.chemical ? {
        chemical: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HazardSeverity): {
    low: null;
} | {
    severe: null;
} | {
    extreme: null;
} | {
    moderate: null;
} {
    return value == HazardSeverity.low ? {
        low: null
    } : value == HazardSeverity.severe ? {
        severe: null
    } : value == HazardSeverity.extreme ? {
        extreme: null
    } : value == HazardSeverity.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SurvivalCategory): {
    fire: null;
} | {
    food: null;
} | {
    navigation: null;
} | {
    shelter: null;
} | {
    water: null;
} {
    return value == SurvivalCategory.fire ? {
        fire: null
    } : value == SurvivalCategory.food ? {
        food: null
    } : value == SurvivalCategory.navigation ? {
        navigation: null
    } : value == SurvivalCategory.shelter ? {
        shelter: null
    } : value == SurvivalCategory.water ? {
        water: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TriageStatus): {
    minor: null;
} | {
    delayed: null;
} | {
    deceased: null;
} | {
    immediate: null;
} {
    return value == TriageStatus.minor ? {
        minor: null
    } : value == TriageStatus.delayed ? {
        delayed: null
    } : value == TriageStatus.deceased ? {
        deceased: null
    } : value == TriageStatus.immediate ? {
        immediate: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FirstAidCategory): {
    CPR: null;
} | {
    bleeding: null;
} | {
    shock: null;
} | {
    burns: null;
} | {
    fractures: null;
} {
    return value == FirstAidCategory.CPR ? {
        CPR: null
    } : value == FirstAidCategory.bleeding ? {
        bleeding: null
    } : value == FirstAidCategory.shock ? {
        shock: null
    } : value == FirstAidCategory.burns ? {
        burns: null
    } : value == FirstAidCategory.fractures ? {
        fractures: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FirstAidSeverity): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    moderate: null;
} {
    return value == FirstAidSeverity.low ? {
        low: null
    } : value == FirstAidSeverity.high ? {
        high: null
    } : value == FirstAidSeverity.critical ? {
        critical: null
    } : value == FirstAidSeverity.moderate ? {
        moderate: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
